name: Run Python Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Triggered manually

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements

    - name: Run DirectPlansAMC.py
      run: python /home/runner/work/MF_Holding_moneycontrol/MF_Holding_moneycontrol/src/DirectPlansAMC.py

    - name: Run createBulkCsv.py
      run: python /home/runner/work/MF_Holding_moneycontrol/MF_Holding_moneycontrol/src/createBulkCsv.py

    - name: Run utiNifty.py
      run: python /home/runner/work/MF_Holding_moneycontrol/MF_Holding_moneycontrol/src/utiNifty.py
